// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwBKrpi-TnCBGA3roD4cPzD6YgkJB1k10',
    appId: '1:859268588095:web:97f1a0462b935529640e8a',
    messagingSenderId: '859268588095',
    projectId: 'crudtutorial-251d5',
    authDomain: 'crudtutorial-251d5.firebaseapp.com',
    storageBucket: 'crudtutorial-251d5.firebasestorage.app',
    measurementId: 'G-31YD0SPJY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD98u4k1XRooi_giBC2AxVlqZ0v-4LhzfM',
    appId: '1:859268588095:android:4e617149227c3c12640e8a',
    messagingSenderId: '859268588095',
    projectId: 'crudtutorial-251d5',
    storageBucket: 'crudtutorial-251d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBgW-tpvARoCG3I1MhStB0l_8kN4q7Kmk',
    appId: '1:859268588095:ios:88d0130cf5ff22ad640e8a',
    messagingSenderId: '859268588095',
    projectId: 'crudtutorial-251d5',
    storageBucket: 'crudtutorial-251d5.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );
}
